[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/api/submit-vote"
  to = "/.netlify/functions/submit-vote"
  status = 200

[[redirects]]
  from = "/api/get-results"
  to = "/.netlify/functions/get-results"
  status = 200